spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false

  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations:
        - classpath:database/schema.sql

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000