spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false

  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations:
        - classpath:database/schema.sql